In [34]:
!pip install xlrd==2.0.1

import pandas as pd

Requirement already satisfied: xlrd==2.0.1 in /usr/local/lib/python3.10/dist-packages (2.0.1)

In [2]:
from google.colab import files
uploaded = files.upload()

Saving GSAF5.xls to GSAF5.xls

In [66]:
shark_df = pd.read_excel('GSAF5.xls')
#to use collab files, we have used a Relative Path (just the name of the file, not the whole path)

In [67]:
shark_df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,15 Mar 2024,2024.0,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,F,13,...,Tiger shark,"Yahoo News, 3/15/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04 Mar 2024,2024.0,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,Matthew White,M,NaN,...,Tiger shark 8',"Surfer, 3/6/2024F",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02 Mar-2024,2024.0,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,NaN,F,11,...,3' to 4' shark,"Hawaii News Now, 3/4/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25 Feb-2024,2024.0,Unprovoked,AUSTRALIA,Western Australia,"Sandlnd Island, Jurian Bay",NaN,female,F,46,...,Tiger shark,"WA Today, 2/26/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,14 Feb-2024,2024.0,Unprovoked,INDIA,Maharashtra,"Vaitarna River, Palghar District",Fishing,Vicky Suresh Govari,M,32,...,"Bull shark, 7'","Times of India, 2/14/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
shark_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6969 entries, 0 to 6968
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            6944 non-null   object
 1   Year            6942 non-null   float64
 2   Type            6926 non-null   object
 3   Country         6894 non-null   object
 4   State           6462 non-null   object
 5   Location        6379 non-null   object
 6   Activity        6358 non-null   object
 7   Name            6724 non-null   object
 8   Sex             6365 non-null   object
 9   Age             3950 non-null   object
 10  Injury          6909 non-null   object
 11  Unnamed: 11     6382 non-null   object
 12  Time            3418 non-null   object
 13  Species         3812 non-null   object
 14  Source          6925 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6819 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

In [69]:
shark_df.isna().sum()

Date                25
Year                27
Type                43
Country             75
State              507
Location           590
Activity           611
Name               245
Sex                604
Age               3019
Injury              60
Unnamed: 11        587
Time              3551
Species           3157
Source              44
pdf                170
href formula       150
href               173
Case Number        171
Case Number.1      172
original order     170
Unnamed: 21       6968
Unnamed: 22       6967
dtype: int64

In [70]:
shark_df.duplicated().sum()

24

In [71]:
shark_df.duplicated(subset=['Date',"Year","Type","Country",	"State","Location",	"Activity",	"Name",	"Sex","Age"]).sum()

32

In [72]:
#Standardize Column Names:
shark_df.columns = shark_df.columns.str.lower().str.replace(' ', '_')
shark_df.columns = shark_df.columns.str.lower().str.replace('.', '_')

shark_df.columns

# Ensure 'age' column is numeric
shark_df['age'] = pd.to_numeric(shark_df['age'], errors='coerce')

# Clean the data: Remove leading/trailing whitespace
shark_df = shark_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Normalize text: Convert all text to lowercase
shark_df = shark_df.apply(lambda x: x.str.lower() if x.dtype == "object" else x)

# Add a name for the "fatal = y/n"
shark_df.rename(columns= {'unnamed:_11': 'fatal'}, inplace=True)

In [73]:
shark_df.head()

,date,year,type,country,state,location,activity,name,sex,age,...,species_,source,pdf,href_formula,href,case_number,case_number_1,original_order,unnamed:_21,unnamed:_22
0,15 mar 2024,2024.0,unprovoked,australia,queensland,bargara beach,swimming,brooklyn sauer,f,13.0,...,tiger shark,"yahoo news, 3/15/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04 mar 2024,2024.0,unprovoked,usa,hawaii,"old man's, waikiki",surfing,matthew white,m,NaN,...,tiger shark 8',"surfer, 3/6/2024f",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02 mar-2024,2024.0,unprovoked,usa,hawaii,"rainbows, oahu",swimming,NaN,f,11.0,...,3' to 4' shark,"hawaii news now, 3/4/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25 feb-2024,2024.0,unprovoked,australia,western australia,"sandlnd island, jurian bay",NaN,female,f,46.0,...,tiger shark,"wa today, 2/26/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,14 feb-2024,2024.0,unprovoked,india,maharashtra,"vaitarna river, palghar district",fishing,vicky suresh govari,m,32.0,...,"bull shark, 7'","times of india, 2/14/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
# Drop the columns
columns_to_drop = ['unnamed:_22', 'unnamed:_21', 'original_order', 'href', 'href_formula', 'pdf']
shark_df = shark_df.drop(columns=columns_to_drop)

# Display the first few rows to verify
shark_df.head()

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal,time,species_,source,case_number,case_number_1
0,15 mar 2024,2024.0,unprovoked,australia,queensland,bargara beach,swimming,brooklyn sauer,f,13.0,"minor injuries to back, abdomen and legs",NaN,16h00,tiger shark,"yahoo news, 3/15/2024",NaN,NaN
1,04 mar 2024,2024.0,unprovoked,usa,hawaii,"old man's, waikiki",surfing,matthew white,m,NaN,"no injury, shark bit surfboard",n,NaN,tiger shark 8',"surfer, 3/6/2024f",NaN,NaN
2,02 mar-2024,2024.0,unprovoked,usa,hawaii,"rainbows, oahu",swimming,NaN,f,11.0,lacerations to left foot,n,13h30,3' to 4' shark,"hawaii news now, 3/4/2024",NaN,NaN
3,25 feb-2024,2024.0,unprovoked,australia,western australia,"sandlnd island, jurian bay",NaN,female,f,46.0,leg bitten,n,11h30,tiger shark,"wa today, 2/26/2024",NaN,NaN
4,14 feb-2024,2024.0,unprovoked,india,maharashtra,"vaitarna river, palghar district",fishing,vicky suresh govari,m,32.0,calf of lower left leg injured,n,NaN,"bull shark, 7'","times of india, 2/14/2024",NaN,NaN

In [75]:
#drops any row that has less than 3 valid values
shark_df.dropna(thresh=3, inplace=True)

In [76]:
shark_df = shark_df.drop_duplicates()
shark_df

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal,time,species_,source,case_number,case_number_1
0,15 mar 2024,2024.0,unprovoked,australia,queensland,bargara beach,swimming,brooklyn sauer,f,13.0,"minor injuries to back, abdomen and legs",NaN,16h00,tiger shark,"yahoo news, 3/15/2024",NaN,NaN
1,04 mar 2024,2024.0,unprovoked,usa,hawaii,"old man's, waikiki",surfing,matthew white,m,NaN,"no injury, shark bit surfboard",n,NaN,tiger shark 8',"surfer, 3/6/2024f",NaN,NaN
2,02 mar-2024,2024.0,unprovoked,usa,hawaii,"rainbows, oahu",swimming,NaN,f,11.0,lacerations to left foot,n,13h30,3' to 4' shark,"hawaii news now, 3/4/2024",NaN,NaN
3,25 feb-2024,2024.0,unprovoked,australia,western australia,"sandlnd island, jurian bay",NaN,female,f,46.0,leg bitten,n,11h30,tiger shark,"wa today, 2/26/2024",NaN,NaN
4,14 feb-2024,2024.0,unprovoked,india,maharashtra,"vaitarna river, palghar district",fishing,vicky suresh govari,m,32.0,calf of lower left leg injured,n,NaN,"bull shark, 7'","times of india, 2/14/2024",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6939,before 1903,0.0,unprovoked,australia,western australia,roebuck bay,diving,male,m,NaN,fatal,y,NaN,NaN,"h. taunton; n. bartlett, p. 234",nd.0005,nd.0005
6940,before 1903,0.0,unprovoked,australia,western australia,NaN,pearl diving,ahmun,m,NaN,fatal,y,NaN,NaN,"h. taunton; n. bartlett, pp. 233-234",nd.0004,nd.0004
6941,1900-1905,0.0,unprovoked,usa,north carolina,ocracoke inlet,swimming,coast guard personnel,m,NaN,fatal,y,NaN,NaN,"f. schwartz, p.23; c. creswell, gsaf",nd.0003,nd.0003
6942,1883-1889,0.0,unprovoked,panama,NaN,"panama bay 8ºn, 79ºw",NaN,jules patterson,m,NaN,fatal,y,NaN,NaN,"the sun, 10/20/1938",nd.0002,nd.0002
6943,1845-1853,0.0,unprovoked,ceylon (sri lanka),eastern province,"below the english fort, trincomalee",swimming,male,m,15.0,"fatal. ""shark bit him in half, carrying away t...",y,NaN,NaN,s.w. baker,nd.0001,nd.0001

In [77]:
shark_df['species_'].unique()

array(['tiger shark', "tiger shark 8'", "3' to 4' shark", ...,
       "12' tiger shark", 'blue pointers',
       'said to involve a grey nurse shark that leapt out of the water and  seized the boy but species identification is questionable'],
      dtype=object)

In [78]:
shark_df['species_'].nunique()

1563

In [83]:
import re

# Mapping dictionary for replacements
mapping_dict = {
    r'\bjuvenile\s+bull\s+shark\b': 'bull shark',
    r'\bbull\s+shark\b': 'bull shark',
    r'\bwhite\s+shark\b': 'white shark',
    r'\btiger\s+shark\b': 'tiger shark',
    r'\bhammerhead\b': 'hammerhead shark',
    r'\bblacktip\b': 'blacktip shark',
    r'\bunknown\b': 'unknown',
    r'\bnot\s+confirmed\b': 'unknown'
}

# Function to apply mapping dictionary using regex
def apply_mapping(s):
    if isinstance(s, str):
        for pattern, replacement in mapping_dict.items():
            if re.search(pattern, s, flags=re.IGNORECASE):
                return replacement
    return 'unknown'  # Handle non-string values gracefully

# Ensure all values in 'species_' are strings
shark_df['species_'] = shark_df['species_'].astype(str)

# Apply the mapping using the apply method with a lambda function
shark_df['species_'] = shark_df['species_'].apply(lambda x: apply_mapping(x))

# Display the result
shark_df

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal,time,species_,source,case_number,case_number_1
0,15 mar 2024,2024.0,unprovoked,australia,queensland,bargara beach,swimming,brooklyn sauer,f,13.0,"minor injuries to back, abdomen and legs",NaN,16h00,tiger shark,"yahoo news, 3/15/2024",NaN,NaN
1,04 mar 2024,2024.0,unprovoked,usa,hawaii,"old man's, waikiki",surfing,matthew white,m,NaN,"no injury, shark bit surfboard",n,NaN,tiger shark,"surfer, 3/6/2024f",NaN,NaN
2,02 mar-2024,2024.0,unprovoked,usa,hawaii,"rainbows, oahu",swimming,NaN,f,11.0,lacerations to left foot,n,13h30,unknown,"hawaii news now, 3/4/2024",NaN,NaN
3,25 feb-2024,2024.0,unprovoked,australia,western australia,"sandlnd island, jurian bay",NaN,female,f,46.0,leg bitten,n,11h30,tiger shark,"wa today, 2/26/2024",NaN,NaN
4,14 feb-2024,2024.0,unprovoked,india,maharashtra,"vaitarna river, palghar district",fishing,vicky suresh govari,m,32.0,calf of lower left leg injured,n,NaN,bull shark,"times of india, 2/14/2024",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6939,before 1903,0.0,unprovoked,australia,western australia,roebuck bay,diving,male,m,NaN,fatal,y,NaN,unknown,"h. taunton; n. bartlett, p. 234",nd.0005,nd.0005
6940,before 1903,0.0,unprovoked,australia,western australia,NaN,pearl diving,ahmun,m,NaN,fatal,y,NaN,unknown,"h. taunton; n. bartlett, pp. 233-234",nd.0004,nd.0004
6941,1900-1905,0.0,unprovoked,usa,north carolina,ocracoke inlet,swimming,coast guard personnel,m,NaN,fatal,y,NaN,unknown,"f. schwartz, p.23; c. creswell, gsaf",nd.0003,nd.0003
6942,1883-1889,0.0,unprovoked,panama,NaN,"panama bay 8ºn, 79ºw",NaN,jules patterson,m,NaN,fatal,y,NaN,unknown,"the sun, 10/20/1938",nd.0002,nd.0002
6943,1845-1853,0.0,unprovoked,ceylon (sri lanka),eastern province,"below the english fort, trincomalee",swimming,male,m,15.0,"fatal. ""shark bit him in half, carrying away t...",y,NaN,unknown,s.w. baker,nd.0001,nd.0001

In [84]:
shark_df['species_'].nunique()

6

In [86]:
shark_df['species_'].unique()

array(['tiger shark', 'unknown', 'bull shark', 'blacktip shark',
       'white shark', 'hammerhead shark'], dtype=object)